class GlobalConstants:
    HOST = '192.168.1.100'
    PORT = 7771

    START_CODE = 'aa'
    END_CODE = '81'

    HEX_DIGITS_PER_BYTE = 2
    PACKET_LEN_START_INDEX = 1 * HEX_DIGITS_PER_BYTE
    PACKET_LEN_END_INDEX = 2 * HEX_DIGITS_PER_BYTE
    DATA_COUNTER_START_INDEX = 3 * HEX_DIGITS_PER_BYTE
    DATA_COUNTER_END_INDEX = 6 * HEX_DIGITS_PER_BYTE
    CHECKSUM_START_INDEX = 7 * HEX_DIGITS_PER_BYTE
    CHECKSUM_END_INDEX = 10 * HEX_DIGITS_PER_BYTE
    MSG_CODE = 11 * HEX_DIGITS_PER_BYTE
    DATA_PAYLOAD_START_INDEX = 12 * HEX_DIGITS_PER_BYTE

    START_END_CODE_LENGTH = 1 * HEX_DIGITS_PER_BYTE
    BUF_LEN_LENGTH = PACKET_LEN_END_INDEX - PACKET_LEN_START_INDEX
    TCP_LEN_LENGTH = 8
    AVERAGE_DATA_LEN = 620

    DATA_BLOCK_LEN_HEX = 4

    DATA_PARAMS_LEN = 12  # data check parameters length- in bytes
    BYTE_LEN = 8

    DATA_INDEX_LENGTH = 8

    HEX_BASE = 16
    MAX_DATA_INDEX = HEX_BASE ^ (DATA_INDEX_LENGTH) - 1
