class GlobalConstants:

    # protocol related constants
    START_CODE = 'aa'
    END_CODE = '81'

    BYTE_SIZE = 8

    HEX_DIGITS_PER_BYTE = 2
    PACKET_LEN_START_INDEX = 1 * HEX_DIGITS_PER_BYTE
    PACKET_LEN_END_INDEX = 3 * HEX_DIGITS_PER_BYTE
    DATA_COUNTER_START_INDEX = 3 * HEX_DIGITS_PER_BYTE
    DATA_COUNTER_END_INDEX = 7 * HEX_DIGITS_PER_BYTE
    CHECKSUM_START_BYTE = 7
    CHECKSUM_START_INDEX = CHECKSUM_START_BYTE * HEX_DIGITS_PER_BYTE
    CHECKSUM_END_INDEX = 11 * HEX_DIGITS_PER_BYTE
    MSG_CODE_BYTE = 11
    MSG_CODE_START_INDEX = MSG_CODE_BYTE * HEX_DIGITS_PER_BYTE
    MSG_CODE_END_INDEX = (MSG_CODE_BYTE + 1) * HEX_DIGITS_PER_BYTE
    DATA_PAYLOAD_START_INDEX = 12 * HEX_DIGITS_PER_BYTE

    MAX_PACKET_LEN = 256

    START_END_CODE_LENGTH = 1 * HEX_DIGITS_PER_BYTE
    BUF_LEN_LENGTH = PACKET_LEN_END_INDEX - PACKET_LEN_START_INDEX
    TCP_LEN_LENGTH = 8
    HEADER_LEN = 13 * HEX_DIGITS_PER_BYTE
    PAYLOAD_INDICES_LEN_BYTE = 2
    PAYLOAD_INDICES_LEN = PAYLOAD_INDICES_LEN_BYTE * HEX_DIGITS_PER_BYTE

    DATA_BLOCK_LEN_HEX = 4

    DATA_PARAMS_LEN = 12  # data check parameters length- in bytes
    BYTE_LEN = 8

    DATA_INDEX_LENGTH = 8

    HEX_BASE = 168

    SERIAL_BYTE_LEN = 10

    MESSAGE_CODE_DICT = {
        'HEARTBEAT_REQUEST': 0x00,
        'HEARTBEAT_RESPONSE': 0x01,
        'RESET_REQUEST': 0x02,
        'RESET_RESPONSE': 0x03,
        'ECC_CHECKED': 0x04,
        'ECC_PERIOD_CHANGE': 0x05,
        'ADC_DATA': 0x06
    }

    # max values
    MAX_DATA_INDEX = 4294967295
    HEARTBEAT_ID_MAX = 4294967295
    DATA_INDEX_MAX = 4294967295

    # Communication error related constants
    COM_ERROR_TYPES = {'NO RESPONSE', 'MISSING START CODE', 'MISSING END CODE', 'UNORDERED DATA_CNT',
                       'UNORDERED DATA CONTENT'}

    # ECC check related constants
    MEM_ERROR_INDEX_START_BYTE = 0
    MEM_ERROR_INDEX_START = MEM_ERROR_INDEX_START_BYTE * HEX_DIGITS_PER_BYTE
    MEM_ERROR_INDEX_END_BYTE = 2
    MEM_ERROR_INDEX_END = MEM_ERROR_INDEX_END_BYTE * HEX_DIGITS_PER_BYTE
    ERROR_CNT_START_BYTE = 2
    ERROR_CNT_START = ERROR_CNT_START_BYTE * HEX_DIGITS_PER_BYTE
    ERROR_CNT_END_BYTE = 5
    ERROR_CNT_END = ERROR_CNT_END_BYTE * HEX_DIGITS_PER_BYTE
    OVERFLOW_START_BYTE = 5
    OVERFLOW_START = OVERFLOW_START_BYTE * HEX_DIGITS_PER_BYTE
    OVERFLOW_END_BYTE = 6
    OVERFLOW_END = OVERFLOW_END_BYTE * HEX_DIGITS_PER_BYTE
    MEM_ADDRESSES_START_BYTE = 7
    MEM_ADDRESSES_START = MEM_ADDRESSES_START_BYTE * HEX_DIGITS_PER_BYTE
    MEM_ADDRESS_LEN_BYTE = 3
    MEM_ADDRESSES_LEN = MEM_ADDRESS_LEN_BYTE * HEX_DIGITS_PER_BYTE

    ADDRESS_BYTE_NUM = 3

    ECC_CHECK_PERIODS = {
        100: 0,
        1000: 1,
        10000: 2,
        60000: 3
    }

    MAX_ADDRESSES_ECC = 39

    # HEARTBEAT related constants
    HEARTBEAT_LEN = 24
    HEARTBEAT_RESPONSE_LEN = 21 * HEX_DIGITS_PER_BYTE

    HEARTBEAT_PERIOD_START = 0
    HEARTBEAT_PERIOD_END = 1 * HEX_DIGITS_PER_BYTE
    HEARTBEAT_ID_START = 1 * HEX_DIGITS_PER_BYTE
    HEARTBEAT_ID_END = (1 + 4) * HEX_DIGITS_PER_BYTE

    HEARTBEAT_PERIODS = {
        100: 0,
        250: 1,
        500: 2,
        1000: 3
    }

    # RESET related constants
    RESET_PURPOSES = {
        0x40: 'SYST',
        0x20: 'WDT',
        0x10: 'EXT',
        0x08: 'NVM',
        0x01: 'POR'
    }
